### PR TITLE
Add backend for selectrum

### PR DESCRIPTION
**Pull request by clemera**
As promised I added a backend for selectrum. I followed the implementations for the other backends let me know if you want me something to add/change. Thanks!

### CODE REVIEW

**Comment by DarwinAwardWinner** [comment]
This looks good. I assume you've been using this yourself and have found that it works?

**Comment by clemera** [comment]
Yep, I'm using this as my current amx backend.

**Comment by clemera** [comment]
Should I add the backend to `amx-completing-read-auto` as well?

**Comment by DarwinAwardWinner** [comment]
I've merged this as 1cda9dd, and added auto support and tests in 7fb7b87.

**Comment by DarwinAwardWinner** [comment]
Oh, also, some of the tests were added in 1fcc44b (by mistake; they *should* have been in https://github.com/DarwinAwardWinner/amx/commit/7fb7b874291e0cdeb1f0acb18564a686ec86788d).

**Comment by clemera** [comment]
Very nice, thanks!

**Pull request closed without merging**
